config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "boards#index"
  resources :boards, only: [:show, :new, :create, :edit, :update, :destroy]
  
  resources :board do
    resources :tasks do
      resources :comments, only: [:show,:new, :create]
    end
  end
  resource :profile, only: [:show, :edit, :update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :tasks
  validates :title, presence: true
  validates :content, presence: true

  def comment_count
    comments.count
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar


  def age
    return '不明' unless birthday.present?
    years = Time.zone.now.year - birthday.year
    days = Time.zone.now.yday - birthday.yday

    if days < 0
      "#{years - 1}歳"
    else
      "#{years}歳"
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  has_one_attached :eyecatch
  has_many :comments
  belongs_to :board, optional: true
  belongs_to :user,  optional: true

  def comment_count
    comments.count
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :boards, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :content, dependent: :destroy
  has_one :profile, dependent: :destroy

  delegate :birthday, :age, :gender, to: :profile, allow_nil: true
  
  def has_written?(board)
    boards.exists?(id: board.id)
  end
  def task_has_written?(task)
    tasks.exists?(id: task.id)
  end

  def author_name
    user.display_name
  end


  def prepare_profile
    profile || build_profile
  end


  def display_name
    profile&.nickname || self.email.split('@').first
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.png'
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show]
  before_action :authenticate_user!, only:[:new, :create, :edit, :update, :destroy]

  def index
    @boards = Board.all
  end

  def show
    @tasks = @board.tasks
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to board_path(@board), notice: '保存できたよ！'
    else
      flash.now[:error] = '保存に失敗したよ'
      render:new
    end
  end

  def edit
    @board = current_user.boards.find(params[:id])
  end

  def update
    @board = current_user.boards.find(params[:id])
  if @board.update(board_params)
    redirect_to board_path(@board), notice: '更新出来ました'
  else
    flash.now[:error] = '更新出来ませんでした'
    render :edit
  end
  end

  def destroy
    board = current_user.boards.find(params[:id])
    board.destroy!
    redirect_to root_path, notice: '削除に成功しました'
  end

private 
def board_params
    params.require(:board).permit(:title, :content,)
end

def set_board
  @board = Board.find(params[:id])
end 

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def new
    @board = Board.find(params[:board_id])
    task = Task.find(params[:task_id])
    @comment = task.comments.build(params[:id])
  end

  def create
    task = Task.find(params[:task_id])
    @board = Board.find(params[:board_id])
    @comment = task.comments.create(comment_params)
    if @comment.save!
      redirect_to board_task_path(@board, task), notice: '保存できたよ！'
    end
  end  

    private
    def comment_params 
      params.require(:comment).permit(:content, :user_id, :board_id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def edit
    @profile = current_user.prepare_profile
  end

  def show
    @profile = current_user.profile
  end

  def update
    @profile = current_user.prepare_profile
    @profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profile_path, notice: '保存しました！'
    else   
      flash.now[:error] = '更新出来ませんでした'
      render :edit
    end
  end


private 
def profile_params
  params.require(:profile).permit(
    :avatar,
    :nickname,
    :introduction,
    :birthday,
    :subscribed,
    :user_id
  )
end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, only:[:new, :create, :edit, :update, :destroy]
  
  
  def show
    @task = Task.find(params[:id])
    @board = Board.find(params[:board_id])
    @comments = @task.comments
  end

  
  def new
    board = Board.find(params[:board_id])
    @task = board.tasks.build
  end
  
  def create
    board = Board.find(params[:board_id])
    @task = board.tasks.create(task_params)
    if @task.save!
      redirect_to board_path(board), notice: '保存できたよ'
    else
      flash.now[:error] = '保存に失敗したよ'
      render:new
    end
  end
  
  def edit
    @task = Task.find(params[:id])
    @board = Board.find(params[:board_id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
    redirect_to board_task_path(id: @task, board_id: @board), notice: '更新出来ました'
    else
    flash.now[:error] = '更新出来ませんでした'
    render :edit
    end
  end

  def destroy
    @board = Board.find(params[:board_id])
    @task = current_user.tasks.find(params[:id])
    @task.destroy!
    redirect_to board_path(id: @board), notice: '削除に成功しました'
  end

private

def task_params
  params.require(:task).permit(:title, :content, :user_id, :eyecatch)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/boards/edit.html.haml
.container
  %h1 Edit BOARD
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @board, local: true ) do |f|
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'Title'
    %div
      = f.text_field :title, class:'text'
    %div
      = f.label :content, 'Content'
    %div
      = f.text_area :content, class:'content'
    %div
      = f.submit '保存', class:'btn-primary'

app/views/boards/index.html.haml
.container
  %h1 ALL Boards
  = link_to new_board_path do
    .card.border-info.mb-3{:style => "max-width: 20rem;"}
      .card-body
        ＋ Add New Board
  - @boards.each do |board|
    .card.bg-secondary.mb-3{:style => "max-width: 20rem;"}
      .card-header 
      -if user_signed_in? && current_user.has_written?(board)
        .text-right
          .article_detail_actions
            .dropdown
              = image_tag 'actions.svg', class: 'dropbtn'
              .dropdown-content.mini
                = link_to 'Edit', edit_board_path(board)
                = link_to 'Delete',  board_path(board), data: {method: 'delete', confirm: '本当に削除しても宜しいですか？' }
      = link_to board_path(board) do            
        .card-body
          %h4.card-title 
            = truncate(board.title)
          %p.card-text 
            = truncate(board.content)
        .card_detail
          = image_tag board.user.avatar_image  

app/views/boards/new.html.haml
.container
  %h1 NEW BOARD
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @board, local: true ) do |f|
    %div
      = f.label :title, 'Title'
    %div
      = f.text_field :title, class:'text'
    %div
      = f.label :content, 'Content'
    %div
      = f.text_area :content, class:'content'
    %div
      = f.submit '保存', class:'btn-primary'

app/views/boards/show.html.haml
.card.mb-3
  .card-body
    %h5.card-title
      = @board.title
    -if user_signed_in? && current_user.has_written?(@board)
      .text-right
        .article_detail_actions
          .dropdown
            = image_tag 'actions.svg', class: 'dropbtn'
            .dropdown-content.mini
              = link_to 'Edit', edit_board_path(@board)
              = link_to 'Delete', board_path(@board), data: {method: 'delete', confirm: '本当に削除しても宜しいですか？' }
  .card-body
    %p.card-text 
      = @board.content            
.container      
  = link_to new_board_task_path(@board) do
    .card.border-info.mb-3{:style => "max-width: 20rem;"}
      .card-body
        ＋ Add New Card
.container
  .card-task      
    - @tasks.each do |task|
      .card.bg-secondary.mb-3{:style => "max-width: 20rem;"}
        = link_to board_task_path(board_id: @board, id: task) do
          .card-header 
            -if task.eyecatch.attached?
              .card_img
                = image_tag task.eyecatch, width: '100%', height: '100%'
            .card-body
              %h4.card-title 
                = truncate(task.title)
              %p.card-text 
                = truncate(task.content)  
              .card_detail
                = image_tag task.user.avatar_image    

app/views/comments/new.html.haml
.container
  %h1 NEW COMMENT
  %ul
    - @comment.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @comment, url: board_task_comments_path(@comment.task, board_id: @board), local: true ) do |f|
    %div
      = f.label :content, 'Content'
    %div
      = f.text_area :content, class:'content'
    = f.hidden_field :user_id, value:current_user.id  
    %div
      = f.submit '保存', class:'btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyTodoApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %link{:href => "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    = favicon_link_tag('favicon.ico')
  %body
    - if user_signed_in?
      %nav.navbar.navbar-expand-lg.navbar-light.bg-light
        %div.navbar-brand  
          = link_to "Boards", root_path,  class: "navbar-brand "
        %button.navbar-toggler{"aria-controls" => "navbarColor03", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarColor03", "data-toggle" => "collapse", :type => "button"}
          = image_tag current_user.avatar_image, class: 'header_avatar dropbtn'
          %span.navbar-toggler-icon
        #navbarColor03.collapse.navbar-collapse
          %ul.navbar-nav.mr-auto
            %li.nav-item
              = link_to "Profile", profile_path, class: "nav-link"
            %li.nav-item
              = link_to "Logout", destroy_user_session_path, data: { method: 'delete' }, class: "nav-link"
    - else 
      %nav.navbar.navbar-expand-lg.navbar-light.bg-light
        %div.navbar-brand  
          = link_to "Boards", root_path,  class: "navbar-brand "   
        .text-right
          = button_to 'Login', new_user_session_path, class: "btn btn-primary"
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield

app/views/profiles/edit.html.haml
.container
  %ul
  - @profile.errors.full_messages.each do |message|
    %li= message
  = form_with(model: @profile, url: profile_path, method: 'put', local: true ) do |f|
    %div
      = f.label :avatar, 'アバター'
    %div 
      = f.file_field :avatar
    %div 
      = f.label :nickname, 'ハンドルネーム'
    %div
      = f.text_field :nickname, class: 'text'
    %div
      = f.label :introduction, '自己紹介'
    %div
      = f.text_area :introduction
    %div
    -#   = f.label :gender, '性別'
    -# %div 
    -#   =f.select :gender, Profile.genders.map { |k, v| [ I18n.t("enum.genders.#{k}"), k ]}, {}, { class: 'text' }
    %div
      =f.label :birthday, '生年月日'
    %div 
      =f.date_field :birthday, class: 'text'
    %div  
      =f.label :subscribed, '通知を受け取る'
      =f.check_box :subscribed
    = f.hidden_field :user_id, value:current_user.id

    = f.submit '保存', class: 'btn-primary'

app/views/profiles/show.html.haml
.container.profilePage
  .profilePage_user
    .profilePage_user_image
      = image_tag current_user.avatar_image
    .profilePage_user_basicInfo
      .profilePage_user_name
        .profilePage_user_displayName
          #{current_user.display_name} (#{current_user.age})
        .profilePage_user_actionButton
          = link_to 'Edit', edit_profile_path
      .profilePage_user_introduction
        = current_user.profile&.introduction

app/views/tasks/edit.html.haml
.container
  %h1 EDIT CARD
  %ul
    - @task.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @task, url: board_task_path(id: @task, board_id: @board), method: 'put', local: true ) do |f|
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'Title'
    %div
      = f.text_field :title, class:'text'
    %div
      = f.label :content, 'Content'
    %div
      = f.text_area :content, class:'content'

    = f.hidden_field :user_id, value:current_user.id
    %div
      = f.submit '保存', class:'btn-primary'

app/views/tasks/new.html.haml
.container
  %h1 NEW CARD
  %ul
    - @task.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @task, url: board_tasks_path(@task.board), local: true ) do |f|
    %div
      = f.label :Eyecatch, 'eyecatch'  
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'Title'
    %div
      = f.text_field :title, class:'text'
    %div
      = f.label :content, 'Content'
    %div
      = f.text_area :content, class:'content'
    %div
    = f.hidden_field :user_id, value:current_user.id
    %div
      = f.submit '保存', class:'btn-primary'

app/views/tasks/show.html.haml
.container
  .card.mb-3
    .card-body
      -if user_signed_in? && current_user.task_has_written?(@task)
        .text-right
          .article_detail_actions
            .dropdown
              = image_tag 'actions.svg', class: 'dropbtn'
              .dropdown-content.mini
                = link_to 'Edit', edit_board_task_path(board_id: @board, id: @task)
                = link_to 'Delete', board_task_path(id: @task, board_id: @board), data: {method: 'delete', confirm: '本当に削除しても宜しいですか？' }  
      %h5.card-title
        = @task.title
      -if @task.eyecatch.attached?
        .card_img
          = image_tag @task.eyecatch, width: '100%', height: '100%'  
    .card-body
      %p.card-text 
        = @task.content
      .card_detail
        = image_tag @task.user.avatar_image 
      .card_heart    
        = image_tag 'Shape.png'
        %span= @task.comment_count   
.container    
  %h1 Comments

.container
  .card-task      
    - @comments.each do |comment|
      .card.bg-secondary.mb-3{:style => "max-width: 20rem;"}
        .card-body
          = comment.content
        .card_detail
          = image_tag comment.user.avatar_image  

.container      
  = link_to new_board_task_comment_path(board_id: @board, task_id: @task, id: @comment) do
    .card.border-info.mb-3{:style => "max-width: 20rem;"}
      .card-body
        ＋ Add New Comment